community: Switch to upstream ghaction-import-gpg action (#10)
Reference: https://github.com/hashicorp/ghaction-import-gpg/issues/11

The GitHub hosted runners are now running `gpg-agent` by default, which can cause the following error:

```text
Run hashicorp/ghaction-import-gpg@v2.1.0
Run gpg-agent --daemon --default-cache-ttl 7200
gpg-agent[1632]: directory '/home/runner/.gnupg' created
gpg-agent[1632]: directory '/home/runner/.gnupg/private-keys-v1.d' created
gpg-agent: a gpg-agent is already running - not starting a new one
Error: Process completed with exit code 2.
```

The `hashicorp` fork of the `ghaction-import-gpg` action is not maintained and the recommendation is to switch to the upstream action.